export enum ProfessionalType {
  EMPLOYEE = 'EMPLOYEE',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  FREELANCER = 'FREELANCER',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  STUDENT = 'STUDENT',
  OTHER = 'OTHER',
}
