import { ArrowRight, CalendarDays, CircleDollarSign, Download, FileText, Landmark, TrendingUp, WalletCards } from "lucide-react";
import { MetricCard, Panel, ProgressBar, SectionHeading, StatusPill } from "../InvestorUI";

const positions = [
  { name: "Solstice Energy", sector: "Clean energy", stage: "Series B", invested: "$185,000", value: "$238,650", change: "+29.0%", progress: 72, next: "Q2 update · Jun 28" },
  { name: "Impact Fund II", sector: "Diversified impact", stage: "Fund", invested: "$210,000", value: "$224,775", change: "+7.0%", progress: 54, next: "Distribution · Jul 15" },
  { name: "AgriNova", sector: "Agriculture", stage: "Series A", invested: "$145,000", value: "$192,850", change: "+33.0%", progress: 81, next: "Board report · Jul 02" },
  { name: "GreenBuild REIT", sector: "Real assets", stage: "Income", invested: "$120,000", value: "$124,875", change: "+4.1%", progress: 43, next: "Distribution · Jun 30" },
];

export function InvestmentsPage() {
  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">Your positions</h2><p className="mt-1 text-sm text-slate-500">Monitor performance, milestones, and upcoming events.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-xl bg-[#065f46] px-4 py-2.5 text-xs font-bold text-white">Download statement <Download className="h-4 w-4" /></button></div>
      <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-4"><MetricCard label="Active positions" value="12" detail="Across 7 sectors" change="2 added this year" icon={WalletCards} /><MetricCard label="Capital deployed" value="$1.07M" detail="85.6% of portfolio" change="$50K this quarter" icon={Landmark} /><MetricCard label="Next distribution" value="$6,850" detail="Expected Jun 30" change="GreenBuild REIT" trend="neutral" icon={CalendarDays} /><MetricCard label="Lifetime distributions" value="$25,220" detail="From 4 positions" change="18.2% year over year" icon={CircleDollarSign} /></div>

      <div className="grid gap-5 xl:grid-cols-12">
        <Panel className="p-5 sm:p-6 xl:col-span-8"><SectionHeading title="Active investments" description="Latest value and company progress" action={<div className="flex gap-2"><select className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600"><option>All statuses</option><option>Active</option><option>Income</option></select><button type="button" className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">Newest</button></div>} /><div className="mt-5 space-y-3">{positions.map((position) => <article key={position.name} className="rounded-xl border border-slate-100 p-4 transition hover:border-emerald-200 hover:shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><TrendingUp className="h-5 w-5" /></span><div><h3 className="text-sm font-bold text-slate-800">{position.name}</h3><p className="text-xs text-slate-500">{position.sector} · {position.stage}</p></div></div><div className="flex items-center gap-5"><div className="text-right"><span className="block text-xs text-slate-500">Current value</span><strong className="text-sm text-slate-900">{position.value}</strong></div><StatusPill>{position.change}</StatusPill></div></div><div className="mt-4 grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-[1fr_auto]"><div><div className="mb-1.5 flex justify-between text-[11px]"><span className="font-semibold text-slate-500">Milestone progress</span><span className="font-bold text-slate-700">{position.progress}%</span></div><ProgressBar value={position.progress} /></div><div className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-3.5 w-3.5" />{position.next}</div></div></article>)}</div></Panel>
        <div className="space-y-5 xl:col-span-4">
          <Panel className="p-5"><SectionHeading title="Upcoming events" action={<button type="button" className="text-xs font-bold text-emerald-700">Calendar</button>} /><div className="mt-4 space-y-4">{[{ date: "28", month: "JUN", title: "Solstice quarterly update", type: "Portfolio update" }, { date: "30", month: "JUN", title: "GreenBuild distribution", type: "Expected $6,850" }, { date: "02", month: "JUL", title: "AgriNova board report", type: "New document" }].map((event) => <div key={event.title} className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-slate-50 text-center"><span><strong className="block text-sm text-slate-800">{event.date}</strong><span className="block text-[8px] font-bold text-emerald-700">{event.month}</span></span></span><span className="min-w-0"><strong className="block truncate text-sm text-slate-800">{event.title}</strong><span className="text-xs text-slate-500">{event.type}</span></span></div>)}</div></Panel>
          <Panel className="p-5"><SectionHeading title="Documents" /><div className="mt-4 divide-y divide-slate-100">{["Investment confirmations", "Quarterly company updates", "Distribution notices"].map((document, index) => <button key={document} type="button" className="flex w-full items-center gap-3 py-3 text-left first:pt-0 last:pb-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><FileText className="h-4 w-4" /></span><span className="flex-1 text-xs font-semibold text-slate-700">{document}</span><span className="text-[10px] text-slate-400">{index + 2} files</span><ArrowRight className="h-3.5 w-3.5 text-slate-400" /></button>)}</div></Panel>
        </div>
      </div>
    </div>
  );
}
