import { CheckCheck, FileText, MoreHorizontal, Paperclip, Search, Send, ShieldCheck, Video } from "lucide-react";
import { Panel, StatusPill } from "../InvestorUI";

const conversations = [
  { name: "Maya Chen", role: "Solstice Energy", message: "The Q2 investor memo is now ready for review.", time: "10:42 AM", unread: 2, initials: "MC", active: true },
  { name: "Daniel Okafor", role: "Investment advisor", message: "I’ve added notes ahead of our portfolio review.", time: "Yesterday", unread: 1, initials: "DO" },
  { name: "Investra Support", role: "Client success", message: "Your bank account verification is complete.", time: "Mon", unread: 0, initials: "IS" },
  { name: "Sarah Rahman", role: "AgriNova", message: "Thank you for joining our investor update.", time: "May 18", unread: 0, initials: "SR" },
  { name: "Impact Fund II", role: "Fund administration", message: "Distribution notice for Q2 2025.", time: "May 15", unread: 0, initials: "IF" },
];

export function MessagesPage() {
  return (
    <Panel className="min-h-[720px] overflow-hidden">
      <div className="grid min-h-[720px] lg:grid-cols-[340px_minmax(0,1fr)]">
        <aside className="border-b border-slate-200 lg:border-b-0 lg:border-r">
          <div className="border-b border-slate-100 p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Inbox</h2><p className="mt-1 text-xs text-slate-500">3 unread conversations</p></div><button type="button" className="rounded-xl bg-[#065f46] px-3 py-2 text-xs font-bold text-white">New message</button></div><label className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2.5"><Search className="h-4 w-4 text-slate-400" /><input className="w-full bg-transparent text-xs outline-none" placeholder="Search conversations" /></label></div>
          <div className="max-h-[300px] divide-y divide-slate-100 overflow-y-auto lg:max-h-[620px]">{conversations.map((conversation) => <button key={conversation.name} type="button" className={`flex w-full gap-3 p-4 text-left transition hover:bg-slate-50 ${conversation.active ? "bg-emerald-50/70" : ""}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-xs font-bold ${conversation.active ? "bg-emerald-700 text-white" : "bg-slate-100 text-slate-600"}`}>{conversation.initials}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm text-slate-800">{conversation.name}</strong><span className="whitespace-nowrap text-[10px] text-slate-400">{conversation.time}</span></span><span className="mt-0.5 block truncate text-[10px] font-semibold text-emerald-700">{conversation.role}</span><span className="mt-1 flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-xs text-slate-500">{conversation.message}</span>{conversation.unread > 0 && <span className="grid h-5 min-w-5 place-items-center rounded-full bg-emerald-600 px-1 text-[9px] font-bold text-white">{conversation.unread}</span>}</span></span></button>)}</div>
        </aside>

        <section className="flex min-h-[650px] flex-col">
          <header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-700 text-xs font-bold text-white">MC</span><div><div className="flex items-center gap-2"><h3 className="text-sm font-bold text-slate-900">Maya Chen</h3><StatusPill>Verified founder</StatusPill></div><p className="text-xs text-slate-500">Solstice Energy · Online</p></div></div><div className="flex gap-1"><button type="button" className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-50" aria-label="Start video call"><Video className="h-4 w-4" /></button><button type="button" className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-50" aria-label="Conversation options"><MoreHorizontal className="h-4 w-4" /></button></div></header>

          <div className="flex-1 space-y-5 overflow-y-auto bg-slate-50/40 p-5 sm:p-7"><div className="text-center"><span className="rounded-full bg-white px-3 py-1 text-[10px] font-semibold text-slate-400 shadow-sm">Today</span></div><div className="flex max-w-[78%] gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-700 text-[10px] font-bold text-white">MC</span><div><div className="rounded-2xl rounded-tl-sm bg-white p-4 text-xs leading-5 text-slate-600 shadow-sm">Hi Alex, our Q2 investor memo is now ready. We’ve included the regional pilot results and updated capacity forecasts.</div><span className="mt-1 block text-[10px] text-slate-400">10:38 AM</span></div></div><div className="ml-auto max-w-[78%]"><div className="rounded-2xl rounded-tr-sm bg-[#065f46] p-4 text-xs leading-5 text-white">Great—thank you. The commissioning progress looks strong. I’ll review the full memo today.</div><span className="mt-1 flex items-center justify-end gap-1 text-[10px] text-slate-400">10:40 AM <CheckCheck className="h-3 w-3 text-emerald-600" /></span></div><div className="flex max-w-[78%] gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-700 text-[10px] font-bold text-white">MC</span><div><div className="rounded-2xl rounded-tl-sm bg-white p-4 shadow-sm"><p className="text-xs leading-5 text-slate-600">Perfect. I’ve attached it here as well.</p><button type="button" className="mt-3 flex w-full items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 text-left"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><FileText className="h-4 w-4" /></span><span className="flex-1"><strong className="block text-xs text-slate-700">Solstice_Q2_Investor_Memo.pdf</strong><span className="text-[10px] text-slate-400">2.4 MB · PDF</span></span></button></div><span className="mt-1 block text-[10px] text-slate-400">10:42 AM</span></div></div></div>

          <footer className="border-t border-slate-100 p-4"><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold text-slate-400"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600" />Messages and files are encrypted in transit.</div><div className="flex items-end gap-2 rounded-2xl border border-slate-200 bg-white p-2"><button type="button" aria-label="Attach file" className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-50"><Paperclip className="h-4 w-4" /></button><textarea rows={1} className="min-h-10 flex-1 resize-none py-2.5 text-xs outline-none" placeholder="Write a message…" /><button type="button" aria-label="Send message" className="grid h-10 w-10 place-items-center rounded-xl bg-[#065f46] text-white"><Send className="h-4 w-4" /></button></div></footer>
        </section>
      </div>
    </Panel>
  );
}
