import { Bookmark, CheckCircle2, Filter, Leaf, Search, ShieldCheck, SlidersHorizontal, TrendingUp, Users } from "lucide-react";
import { Panel, ProgressBar, StatusPill } from "../InvestorUI";

const deals = [
  { name: "Solstice Grid", sector: "Clean energy", stage: "Series B", summary: "Modular battery systems making renewable power dependable for regional grids.", target: "$4.5M", funded: 76, minimum: "$10,000", returnValue: "18–24%", risk: "Moderate", match: 98, color: "from-emerald-950 to-emerald-700" },
  { name: "AgriNova Systems", sector: "Climate agriculture", stage: "Series A", summary: "Precision irrigation and soil intelligence for water-stressed farming regions.", target: "$2.8M", funded: 61, minimum: "$5,000", returnValue: "16–21%", risk: "Moderate", match: 94, color: "from-lime-800 to-emerald-600" },
  { name: "Medora Health", sector: "Digital health", stage: "Series A", summary: "Affordable remote diagnostics for underserved urban and rural communities.", target: "$3.2M", funded: 48, minimum: "$7,500", returnValue: "20–27%", risk: "Growth", match: 89, color: "from-slate-900 to-sky-800" },
  { name: "Circular Works", sector: "Circular economy", stage: "Growth", summary: "Commercial material recovery infrastructure for fast-growing cities.", target: "$6.0M", funded: 83, minimum: "$15,000", returnValue: "13–18%", risk: "Balanced", match: 86, color: "from-teal-900 to-cyan-700" },
  { name: "EduBridge", sector: "Education access", stage: "Series A", summary: "Employment-linked learning for emerging-market technology professionals.", target: "$2.1M", funded: 57, minimum: "$5,000", returnValue: "17–23%", risk: "Growth", match: 84, color: "from-indigo-950 to-indigo-700" },
  { name: "GreenBuild Income", sector: "Real assets", stage: "Income fund", summary: "Energy-efficient commercial property with quarterly investor distributions.", target: "$12M", funded: 69, minimum: "$25,000", returnValue: "9–12%", risk: "Conservative", match: 81, color: "from-stone-800 to-emerald-800" },
];

export function OpportunitiesPage() {
  return (
    <div className="space-y-5">
      <Panel className="overflow-hidden bg-gradient-to-r from-[#043f31] via-[#065f46] to-[#0c7a59] p-6 text-white sm:p-8">
        <div className="max-w-2xl"><StatusPill tone="green">6 new matches this week</StatusPill><h2 className="mt-4 text-3xl font-bold tracking-tight">Invest in businesses shaping a resilient future.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-emerald-100">Every opportunity is screened for governance, financial quality, leadership, and measurable impact before it reaches your workspace.</p><div className="mt-6 flex flex-wrap gap-3 text-xs font-semibold text-emerald-50"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4" />Verified due diligence</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4" />Investor-fit scoring</span><span className="inline-flex items-center gap-2"><Leaf className="h-4 w-4" />Impact measurement</span></div></div>
      </Panel>

      <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row sm:items-center"><label className="flex flex-1 items-center gap-2 rounded-xl bg-slate-50 px-4 py-3"><Search className="h-4 w-4 text-slate-400" /><input className="w-full bg-transparent text-sm text-slate-700 outline-none placeholder:text-slate-400" placeholder="Search companies, sectors, or themes" /></label><div className="flex gap-2"><button type="button" className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600"><Filter className="h-4 w-4" />Filters</button><button type="button" className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600"><SlidersHorizontal className="h-4 w-4" />Best match</button></div></div>

      <div className="flex gap-2 overflow-x-auto pb-1">{["For you", "Climate", "Healthcare", "Technology", "Real assets", "Income"].map((filter, index) => <button type="button" key={filter} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${index === 0 ? "bg-emerald-800 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{filter}</button>)}</div>

      <div className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3">
        {deals.map((deal, index) => <article key={deal.name} className="group overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-[0_10px_35px_rgba(15,23,42,0.035)] transition hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-lg"><div className={`relative h-32 bg-gradient-to-br ${deal.color} p-5 text-white`}><div className="flex items-start justify-between"><span className="rounded-full bg-white/12 px-3 py-1 text-[10px] font-bold backdrop-blur">{deal.stage}</span><button type="button" className="grid h-9 w-9 place-items-center rounded-full bg-white/10 backdrop-blur hover:bg-white/20" aria-label={`Save ${deal.name}`}><Bookmark className={`h-4 w-4 ${index === 1 ? "fill-white" : ""}`} /></button></div><div className="absolute bottom-4 left-5"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-200">{deal.sector}</p><h3 className="mt-1 text-xl font-bold">{deal.name}</h3></div></div><div className="p-5"><div className="flex items-center justify-between"><StatusPill>{deal.match}% match</StatusPill><span className="inline-flex items-center gap-1 text-[11px] font-semibold text-slate-500"><Users className="h-3.5 w-3.5" />{34 + index * 7} investors</span></div><p className="mt-4 min-h-12 text-xs leading-5 text-slate-500">{deal.summary}</p><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-slate-500">{deal.funded}% funded</span><strong className="text-slate-800">{deal.target}</strong></div><ProgressBar value={deal.funded} /></div><dl className="mt-5 grid grid-cols-3 gap-2 border-t border-slate-100 pt-4"><div><dt className="text-[9px] uppercase tracking-wider text-slate-400">Minimum</dt><dd className="mt-1 text-xs font-bold text-slate-800">{deal.minimum}</dd></div><div><dt className="text-[9px] uppercase tracking-wider text-slate-400">Target IRR</dt><dd className="mt-1 text-xs font-bold text-emerald-700">{deal.returnValue}</dd></div><div><dt className="text-[9px] uppercase tracking-wider text-slate-400">Risk</dt><dd className="mt-1 text-xs font-bold text-slate-800">{deal.risk}</dd></div></dl><button type="button" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#065f46] py-3 text-xs font-bold text-white">Review opportunity <TrendingUp className="h-4 w-4" /></button></div></article>)}
      </div>
    </div>
  );
}
