import { CalendarDays, Download, FileBarChart, FileCheck2, FileText, FolderOpen, Search, ShieldCheck } from "lucide-react";
import { Panel, SectionHeading, StatusPill } from "../InvestorUI";

const reports = [
  { title: "Q2 2025 Portfolio Review", type: "Performance report", date: "Jun 20, 2025", size: "2.8 MB", status: "New", icon: FileBarChart },
  { title: "May 2025 Account Statement", type: "Monthly statement", date: "Jun 01, 2025", size: "864 KB", status: "Ready", icon: FileText },
  { title: "2024 Impact Summary", type: "Impact report", date: "May 14, 2025", size: "4.1 MB", status: "Ready", icon: FileCheck2 },
  { title: "2024 Tax Package", type: "Tax document", date: "Mar 12, 2025", size: "1.2 MB", status: "Ready", icon: ShieldCheck },
  { title: "Q1 2025 Portfolio Review", type: "Performance report", date: "Mar 31, 2025", size: "2.5 MB", status: "Ready", icon: FileBarChart },
];

export function ReportsPage() {
  return (
    <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-3"><Panel className="p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><FolderOpen className="h-5 w-5" /></span><strong className="mt-4 block text-2xl text-slate-950">28</strong><span className="text-xs text-slate-500">Available documents</span></Panel><Panel className="p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><FileBarChart className="h-5 w-5" /></span><strong className="mt-4 block text-2xl text-slate-950">4</strong><span className="text-xs text-slate-500">Portfolio reports this year</span></Panel><Panel className="p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-700"><CalendarDays className="h-5 w-5" /></span><strong className="mt-4 block text-2xl text-slate-950">Jun 30</strong><span className="text-xs text-slate-500">Next statement date</span></Panel></div>

      <Panel className="bg-gradient-to-r from-emerald-50 to-white p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Personalized reporting</p><h2 className="mt-2 text-xl font-bold text-slate-900">Create a custom portfolio report</h2><p className="mt-1 text-sm text-slate-500">Choose a date range, holdings, metrics, and output format.</p></div><button type="button" className="rounded-xl bg-[#065f46] px-5 py-3 text-xs font-bold text-white">Generate report</button></div></Panel>

      <Panel className="overflow-hidden"><div className="p-5 sm:p-6"><SectionHeading title="Document library" description="Statements, reports, confirmations, and tax records" action={<div className="flex gap-2"><label className="hidden items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 md:flex"><Search className="h-3.5 w-3.5 text-slate-400" /><input className="w-36 text-xs outline-none" placeholder="Search documents" /></label><select className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600"><option>All documents</option><option>Statements</option><option>Tax</option></select></div>} /></div><div className="divide-y divide-slate-100">{reports.map(({ title, type, date, size, status, icon: Icon }) => <div key={title} className="flex flex-wrap items-center gap-4 px-5 py-4 hover:bg-slate-50/60 sm:px-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-bold text-slate-800">{title}</h3>{status === "New" && <StatusPill>New</StatusPill>}</div><p className="mt-1 text-xs text-slate-500">{type} · {date}</p></div><span className="text-xs text-slate-400">PDF · {size}</span><button type="button" aria-label={`Download ${title}`} className="rounded-xl border border-slate-200 p-2.5 text-slate-600 hover:bg-emerald-50 hover:text-emerald-700"><Download className="h-4 w-4" /></button></div>)}</div></Panel>

      <div className="grid gap-5 lg:grid-cols-2"><Panel className="p-5"><SectionHeading title="Tax center" description="Documents prepared for annual filing" /><div className="mt-5 rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-700" /><div><strong className="block text-sm text-slate-800">2024 tax package complete</strong><span className="text-xs text-slate-500">All eligible documents are ready.</span></div></div><button type="button" className="mt-4 text-xs font-bold text-emerald-700">Open tax center</button></div></Panel><Panel className="p-5"><SectionHeading title="Delivery preferences" description="Choose how you receive new reports" /><div className="mt-5 space-y-3">{["Email me when a statement is ready", "Quarterly portfolio summary", "Annual impact report"].map((preference, index) => <label key={preference} className="flex items-center justify-between gap-4 text-xs font-semibold text-slate-600"><span>{preference}</span><span className={`relative h-6 w-11 rounded-full ${index < 2 ? "bg-emerald-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${index < 2 ? "right-1" : "left-1"}`} /></span></label>)}</div></Panel></div>
    </div>
  );
}
