import { BellRing, Bookmark, Eye, Leaf, MoreHorizontal, SlidersHorizontal, TrendingUp } from "lucide-react";
import { Panel, ProgressBar, SectionHeading, StatusPill } from "../InvestorUI";

const watched = [
  { name: "AgriNova Systems", sector: "Climate agriculture", stage: "Series A", match: 94, funded: 61, returnValue: "16–21%", minimum: "$5,000", update: "New investor memo", date: "2h ago", alert: true },
  { name: "Circular Works", sector: "Circular economy", stage: "Growth", match: 86, funded: 83, returnValue: "13–18%", minimum: "$15,000", update: "17% allocation remaining", date: "Today", alert: true },
  { name: "Medora Health", sector: "Digital health", stage: "Series A", match: 89, funded: 48, returnValue: "20–27%", minimum: "$7,500", update: "Q2 metrics published", date: "Yesterday", alert: false },
  { name: "GreenBuild Income", sector: "Real assets", stage: "Income fund", match: 81, funded: 69, returnValue: "9–12%", minimum: "$25,000", update: "Due diligence complete", date: "May 18", alert: false },
];

export function WatchlistPage() {
  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">Saved opportunities</h2><p className="mt-1 text-sm text-slate-500">Follow allocation changes, new documents, and deal milestones.</p></div><button type="button" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700"><SlidersHorizontal className="h-4 w-4" />Alert preferences</button></div>

      <div className="grid gap-4 sm:grid-cols-3"><Panel className="p-5"><p className="text-xs font-semibold text-slate-500">Saved opportunities</p><strong className="mt-2 block text-3xl text-slate-950">6</strong><p className="mt-1 text-xs text-emerald-700">2 added this month</p></Panel><Panel className="p-5"><p className="text-xs font-semibold text-slate-500">Active alerts</p><strong className="mt-2 block text-3xl text-slate-950">4</strong><p className="mt-1 text-xs text-slate-500">Allocation and document alerts</p></Panel><Panel className="p-5"><p className="text-xs font-semibold text-slate-500">Average match</p><strong className="mt-2 block text-3xl text-slate-950">88%</strong><p className="mt-1 text-xs text-emerald-700">Strong preference alignment</p></Panel></div>

      <Panel className="overflow-hidden"><div className="p-5 sm:p-6"><SectionHeading title="Your watchlist" description="Sorted by latest activity" action={<button type="button" className="text-xs font-bold text-emerald-700">Compare selected</button>} /></div><div className="divide-y divide-slate-100">{watched.map((deal) => <article key={deal.name} className="p-5 transition hover:bg-emerald-50/20 sm:p-6"><div className="grid gap-5 xl:grid-cols-[minmax(220px,1.4fr)_1fr_1fr_auto]"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Leaf className="h-5 w-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-slate-900">{deal.name}</h3><StatusPill>{deal.match}% match</StatusPill></div><p className="mt-1 text-xs text-slate-500">{deal.sector} · {deal.stage}</p><div className="mt-3 flex items-center gap-2 text-[11px] text-slate-500">{deal.alert ? <BellRing className="h-3.5 w-3.5 text-emerald-600" /> : <Eye className="h-3.5 w-3.5" />}<span>{deal.update}</span><span>· {deal.date}</span></div></div></div><div><div className="flex justify-between text-xs"><span className="text-slate-500">Funding progress</span><strong className="text-slate-800">{deal.funded}%</strong></div><ProgressBar value={deal.funded} className="mt-2" /></div><dl className="grid grid-cols-2 gap-4"><div><dt className="text-[10px] uppercase tracking-wider text-slate-400">Target IRR</dt><dd className="mt-1 text-sm font-bold text-emerald-700">{deal.returnValue}</dd></div><div><dt className="text-[10px] uppercase tracking-wider text-slate-400">Minimum</dt><dd className="mt-1 text-sm font-bold text-slate-800">{deal.minimum}</dd></div></dl><div className="flex items-center gap-2"><button type="button" className="inline-flex items-center gap-2 rounded-xl bg-[#065f46] px-4 py-2.5 text-xs font-bold text-white">Review <TrendingUp className="h-3.5 w-3.5" /></button><button type="button" aria-label="More options" className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><MoreHorizontal className="h-4 w-4" /></button></div></div></article>)}</div></Panel>

      <Panel className="flex flex-col items-start justify-between gap-4 border-dashed p-6 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><Bookmark className="h-4 w-4" /></span><div><h3 className="text-sm font-bold text-slate-800">Two more saved opportunities</h3><p className="mt-1 text-xs text-slate-500">They are currently paused while founders update their fundraising documents.</p></div></div><button type="button" className="text-xs font-bold text-emerald-700">Show paused items</button></Panel>
    </div>
  );
}
